const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),description=document.getElementById('modalText'),overline=document.getElementById('modalOverline'),reportForm=document.getElementById('reportForm'),intakeForm=document.getElementById('intakeForm');
function openModal(type){const report=type==='report';modal.classList.add('open');reportForm.classList.toggle('hidden',!report);intakeForm.classList.toggle('hidden',report);overline.textContent=report?'AI-ASSISTED EXTRACTION · REVIEW REQUIRED':'PATIENT-PROVIDED INFORMATION';title.textContent=report?'Process a medical report':'Add patient information';description.textContent=report?'Paste report text to create a reviewable, source-linked structured record. Nothing here is a diagnosis.':'These details are saved as patient-provided information and never merged with AI-extracted report fields.'}
document.getElementById('intakeBtn').onclick=()=>openModal('intake');document.getElementById('editProfile').onclick=()=>openModal('intake');document.getElementById('processBtn').onclick=()=>openModal('report');document.getElementById('newPatient').onclick=()=>openModal('intake');document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.getElementById('dismissNotice').onclick=e=>e.currentTarget.parentElement.style.display='none';
const safe=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function classify(value,range){if(!range)return{label:'No source range',className:'normal'};let n=(range.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);if(!n.length)return{label:'No source range',className:'normal'};if((/[<]/.test(range)&&value>n[0])||(n.length>1&&value>n[n.length-1]))return{label:'↑ High',className:'high'};if((/[>]/.test(range)&&value<n[0])||(n.length>1&&value<n[0]))return{label:'↓ Low',className:'high'};return{label:'● Normal',className:'normal'}}
function addResult(name,value,unit,range,date){let s=classify(+value,range);document.getElementById('resultsBody').insertAdjacentHTML('afterbegin',`<tr><td><strong>${safe(name)}</strong><small>AI-extracted · ${safe(date)}</small></td><td class="mono ${s.className==='high'?'high-value':''}">${safe(value)} <span>${safe(unit||'')}</span></td><td class="mono muted">${range?safe(range):'Not provided in source'}</td><td><span class="pill ${s.className}">${s.label}</span></td><td><button class="source-link">Pasted report <span>↗</span></button></td></tr>`)}
document.getElementById('extractBtn').onclick=()=>{let source=document.getElementById('reportText').value.trim(),date=document.getElementById('reportDate').value||'Undated report';if(!source){document.getElementById('reportText').focus();return}let count=0;source.split(/\n|;/).map(x=>x.trim()).filter(Boolean).forEach(line=>{let m=line.match(/^([^:\d]{2,}?)\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*([a-zA-Zµ/%]+)?\s*(?:\(\s*([^\)]+)\s*\))?$/i);if(!m)return;let[,name,value,unit='',range='']=m;range=range.replace(/^ref(?:erence)?\s*range\s*[:]?\s*/i,'').trim();if(!/[<>]|\d+\s*(?:-|–|to)\s*\d+/i.test(range))range='';addResult(name.trim(),value,unit,range,date);count++});if(!count){description.textContent='No result rows were recognized. Use one per line, e.g. “Glucose: 92 mg/dL (70 - 99)”.';return}modal.classList.remove('open');document.querySelector('.notice p').innerHTML=`<b>${count} structured result${count===1?'':'s'} extracted for review.</b> Values without source ranges remain unclassified.`;document.querySelector('.notice').style.display='flex'};
intakeForm.onsubmit=e=>{e.preventDefault();let age=patientAge.value,sex=patientSex.value,symptoms=patientSymptoms.value.split(',').map(x=>x.trim()).filter(Boolean),conditions=patientConditions.value.trim(),allergies=patientAllergies.value.trim(),meds=patientMeds.value.trim();if(age||sex)document.querySelector('.identity p').innerHTML=`${age||'38'} years · ${sex||'Female'} · Last updated <strong>Just now</strong>`;if(symptoms.length)document.getElementById('symptomTags').innerHTML=symptoms.map(x=>`<b>${safe(x)}</b>`).join('');if(conditions)conditionsValue.textContent=conditions;if(allergies)allergyValue.innerHTML=`<i>!</i><div><strong>${safe(allergies)}</strong><small>Patient-provided</small></div>`;if(meds)document.querySelector('.meds-card').insertAdjacentHTML('beforeend',`<div class="med"><div class="med-icon">Rx</div><div><strong>${safe(meds)}</strong><small>Patient-provided · verify status</small></div><span>Added</span></div>`);modal.classList.remove('open');document.querySelector('.notice p').innerHTML='<b>Patient-provided information saved.</b> It remains visibly separated from report-extracted data.';document.querySelector('.notice').style.display='flex'};
document.querySelectorAll('.nav-item').forEach(a=>a.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));a.classList.add('active')});
